import { type NextPage } from "next"
import { useRouter } from "next/router"
import { useEffect } from "react"
import Head from "next/head"

const Home: NextPage = () => {
  const router = useRouter()

  useEffect(() => {
    if (router.pathname === "/") {
      void router.push("/login")
    }
  }, [])

  return (
    <>
      <Head>
        <title>Walrusso</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        Hello World!
      </main>
    </>
  )
}

export default Home
